# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nestjsapiingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer 
spec:
  ingressClassName: traefik
  rules:
  - host: nestjsapi.loc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nestjsapiservice
            port:
              number: 3000
  tls: 
  - hosts: 
    - nestjsapi.loc 
    secretName: nestjsapi-cert-tls
              