name: Nest api production deployment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date)"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            BUILD_TIME=${{ steps.date.outputs.date }}
            HASH=${{github.sha}}
            VERSION=1.0.0
          tags: deep1024/nestapi:${{github.sha}}
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
      - name: Update deployment descriptors with the latest build container version
        run: |
          cd deploy
          kustomize edit set image nestapi=deep1024/nestapi:${{github.sha}}
          cat kustomization.yaml
          git config user.name "Github Action Bot"
          git config user.email "<>"
          git add .
          git commit -m "Image name change"
          git push

